python exceptions using try catch statements 
